$.getJSON("http://newsapi.org/v2/top-headlines?country=in&apiKey=1a9c1475289b4941bd167b4ae925272b",function(data){
console.log(data); 
    var icon=data.articles[0].urlToImage;
    var description=data.articles[0].description;
    var title=data.articles[0].title;
    var published=data.articles[0].publishedAt;
    $('.icon').attr('src',icon);
    $('.description').append(description);
    $('.title').append(title);
    $('.published').append(published);
    var icon1=data.articles[1].urlToImage;
    var description1=data.articles[1].description;
    var title1=data.articles[1].title;
    var published1=data.articles[1].publishedAt;
    $('.icon1').attr('src',icon1);
    $('.description1').append(description1);
    $('.title1').append(title1);
    $('.published1').append(published1);
    var icon2=data.articles[2].urlToImage;
    var description2=data.articles[2].description;
    var title2=data.articles[2].title;
    var published2=data.articles[2].publishedAt;
    $('.icon2').attr('src',icon2);
    $('.description2').append(description2);
    $('.title2').append(title2);
    $('.published2').append(published2);
    var icon3=data.articles[3].urlToImage;
    var description3=data.articles[3].description;
    var title3=data.articles[3].title;
    var published3=data.articles[3].publishedAt;
    $('.icon3').attr('src',icon3);
    $('.description3').append(description3);
    $('.title3').append(title3);
    $('.published3').append(published3);
    var icon4=data.articles[4].urlToImage;
    var description4=data.articles[4].description;
    var title4=data.articles[4].title;
    var published4=data.articles[4].publishedAt;
    $('.icon4').attr('src',icon4);
    $('.description4').append(description4);
    $('.title4').append(title4);
    $('.published4').append(published4);
    var icon5=data.articles[5].urlToImage;
    var description5=data.articles[5].description;
    var title5=data.articles[5].title;
    var published5=data.articles[5].publishedAt;
    $('.icon5').attr('src',icon5);
    $('.description5').append(description5);
    $('.title5').append(title5);
    $('.published5').append(published5);
    var icon6=data.articles[6].urlToImage;
    var description6=data.articles[6].description;
    var title6=data.articles[6].title;
    var published6=data.articles[6].publishedAt;
    $('.icon6').attr('src',icon6);
    $('.description6').append(description6);
    $('.title6').append(title6);
    $('.published6').append(published6);
    var icon7=data.articles[7].urlToImage;
    var description7=data.articles[7].description;
    var title7=data.articles[7].title;
    var published7=data.articles[7].publishedAt;
    $('.icon7').attr('src',icon7);
    $('.description7').append(description7);
    $('.title7').append(title7);
    $('.published7').append(published7);
});